### ISSUE TITLE
Can't deploy from Netbeans 9 to Payara 5.184

### ISSUE THREAD

**Issue by youssefgh** [payara/ecosystem-netbeans-plugin#16]
Due to compatibility  [issue](https://github.com/payara/Payara/issues/3284) between JDK 8.191 and Payara 5.183, i had to switch to Payara 5.184

Now when trying to start Payara from netbeans i have : 

`Error: Could not find or load main class [1.8.0|1.8.0u120]-Xbootclasspath.p:.opt.payara5.glassfish.lib.grizzly-npn-bootstrap-1.6.jar`

I figured out that i wasn't using the Payara plugin and i was adding payara as glassfish since when i first installed Netbeans 9 this plugin wasn't yet compatible with it

But even though i installed and used this plugin the issue still persist

### **Environment**

- **Payara Version:** 5.184
- **Edition:** Full
- **JDK Version:** OpenJDK 8u191
- **Operating System:** Ubuntu 18.04

**Comment by lprimak** [comment]
The new Payara NetBeans plugin is about to be released (if it hasn't already) that fixes this problem.
Please look for, and upgrade the Payara NetBeans plugin

Alternatively, you can use admin console and / or asadmin as a workaround

**Comment by youssefgh** [comment]
The last version is still pending verification in the plugin portal, but downgraded to JDK 8.181 and Payara 5.183 until the last version is live
Since the last version is supposed to resolve this issue, I'll close this
Thank you

**Comment by beniamindziurdza** [comment]
Still seems to be unresolved IMHO, Nebeans 9.0 plugin payara 5.184, zulu 8.0.201

Error: Could not find or load main class [1.8.0|1.8.0u120]-Xbootclasspath.p:C:\Users\Beniamin.Dziurdza\payara-5.184\payara5\glassfish.lib.grizzly-npn-bootstrap-1.6.jar

**Comment by beniamindziurdza** [comment]
Still seems to be unresolved: (netbeans 9.0, Payara 5.184)

Error: Could not find or load main class [1.8.0|1.8.0u120]-Xbootclasspath.p:C:\Users\Beniamin.Dziurdza\payara-5.184\payara5\glassfish.lib.grizzly-npn-bootstrap-1.6.jar

**Comment by beniamindziurdza** [comment]
> Still seems to be unresolved: (netbeans 9.0, Payara 5.184, Win7)
> 
> Error: Could not find or load main class [1.8.0|1.8.0u120]-Xbootclasspath.p:C:\Users\Beniamin.Dziurdza\payara-5.184\payara5\glassfish.lib.grizzly-npn-bootstrap-1.6.jar

OK - newest veriosn of plugins seem to work OK.
