### ISSUE TITLE
Can't select Java Platform

### ISSUE THREAD

**Issue by pierrefroy** [payara/ecosystem-netbeans-plugin#19]
![image](https://user-images.githubusercontent.com/2131120/51445054-78f9fa80-1cce-11e9-9089-66d0f6adb54b.png)

**Environment**
Windows 10
JDK 11.0.2
Netbeans 10.0
Payara Plugins installed - OK

**Instructions**
1. Installed Payara Plugins with success
2. Adding Payara 5.184 server configuration with success
3. Can't start server because Java Platform is empty and no Java Platform can be selected even if I click on **Manage Platform** to try to select one.

Unable to run payara without a selected Java Platform.

Thanks!
Pierre Francis

**Comment by jGauravGupta** [comment]
Payara Plugin is compatible with NetBeans IDE JDK 11 platform but Payara Server / Micro (5.184 or less) should explicit define the Java 8 home path. Please add Java 8 platform to start the server.

**Comment by jGauravGupta** [comment]
Internal issue NP-21 to address it.

**Comment by pierrefroy** [comment]
Thanks for the follow-up.

**Comment by baldodavi** [comment]
@jGauravGupta is payara plugin support payara 5.191? Or not yet? I'm able to start payara server from console but not using netbeans...

**Comment by jGauravGupta** [comment]
Hi @baldodavi,

Payara Plugins v1.6 officially supports Payara 5.184 and soon v1.7 will be released with Payara 5.191 support. But the current Plugin v1.6 must also work with Payara 5.191.

So If you are not able to start Payara Server 5.191 from NetBeans IDE with Java 8 platform then please share more info (log, screenshot & error message etc).

**Comment by baldodavi** [comment]
Seems was something strange wrong. Now netbeans is able to start and stop 5.191 with current pluging version. Thanks! (I'm worked a lot on java version probabily I'd wrong Java version on netbeans when issue occourred)

**Comment by pierrefroy** [comment]
The root cause of my problem was actually the fact that Java EE 8 server like Payara are still only compatible with JDK8 and none above 8. So my initial question is rendered irrelevant. I was able to use nomrally the plugins after having based Netbeans on JDK 8.

**Comment by jGauravGupta** [comment]
Fixed by https://github.com/payara/ecosystem-netbeans-plugin/pull/28 and released [Payara plugin v1.8](https://github.com/payara/ecosystem-netbeans-plugin/releases/tag/1.8).
