### ISSUE TITLE
Can't install Payara Plugin on Netbeans 11

### ISSUE THREAD

**Issue by iblader** [payara/ecosystem-netbeans-plugin#31]
Hi Payara :

I am using Netbeans (Version 11) for a while, i installed netbeans from snap store:https://snapcraft.io/netbeans 

I upgraded Payara server from 5.1.182 to 5.1.192, and when I try to install the payara Plugin(version 1.8), I get the following error message:

`
Some plugins require plugin Java DB Database Support to be installed.
The plugin Java DB Database Support is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Payara Common 
Some plugins require plugin Java SE Platforms and Libraries to be installed.
The plugin Java SE Platforms and Libraries is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Payara Common 
Some plugins require plugin Java EE Specifications Support to be installed.
The plugin Java EE Specifications Support is requested in implementation version incubator-netbeans-release-404-on-20190319.  The following plugin is affected:       Payara Server  Some plugins not installed to avoid potential installation problems.`

**Comment by jGauravGupta** [comment]
Hi @iblader,

May you confirm the issue for official binary of NetBeans IDE 11.0 too: https://netbeans.apache.org/download/nb110/nb110.html

**Comment by iblader** [comment]
> Hi @iblader,
> 
> May you confirm the issue for official binary of Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319) too: https://netbeans.apache.org/download/nb110/nb110.html
> 
> May you also please share the Product Version (Help → About) of binary downloaded from the snap store.

Here is the about info:

Product Version: Apache NetBeans IDE 11.0 (Build incubator-netbeans-snap-release-10-on-20190404)
Updates: Updates available to version NetBeans 8.2 Patch 2
Java: 1.8.0_201; Java HotSpot(TM) 64-Bit Server VM 25.201-b09
Runtime: Java(TM) SE Runtime Environment 1.8.0_201-b09
System: Linux version 5.1.8-050108-generic running on amd64; UTF-8; zh_CN (nb)
User directory: /home/kain/snap/netbeans/common/data/11.0
Cache directory: /home/kain/snap/netbeans/common/cache/11.0

**Comment by iblader** [comment]
> 
> 
> Hi @iblader,
> 
> May you confirm the issue for official binary of Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319) too: https://netbeans.apache.org/download/nb110/nb110.html
> 
> May you also please share the Product Version (Help → About) of binary downloaded from the snap store.

Are there any way to force install the plugin to netbeans?

**Comment by jGauravGupta** [comment]
Sorry, You need to install Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319) official binary to use the Payara plugin. Otherwise, you have to build Payara plugin in your current IDE from source.

In the future releases of NetBeans IDE, you don't have to install the plugins, as Payara tools will be integrated soon in the IDE itself.

- https://github.com/apache/netbeans/pull/1290
- https://github.com/apache/netbeans/pull/1297

**Comment by iblader** [comment]
OK, I understand, looking forward to netbeans 11.1 then. 
It is great that payara plugin will integrated to netbeans, good job!

**Comment by iblader** [comment]
Since Netbeans 11.1 has already integrated Payara plugin, so this issue can be closed. Thanks, Payara team.
