### ISSUE TITLE
Error installing Payara Plugins

### ISSUE THREAD

**Issue by Turtugilla** [payara/ecosystem-netbeans-plugin#8]
Im getting the next error window message at installing payara plugins.

```

> Some plugins require plugin Java Common Project API to be installed.
> The plugin Java Common Project API is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Maven Embedder to be installed.
> The plugin Maven Embedder is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Maven Editor Model to be installed.
> The plugin Maven Editor Model is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Maven Projects to be installed.
> The plugin Maven Projects is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Project API to be installed.
> The plugin Project API is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Swing Simple Validation API to be installed.
> The plugin Swing Simple Validation API is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Enhanced Web Browser Functionality to be installed.
> The plugin Enhanced Web Browser Functionality is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Web Common to be installed.
> The plugin Web Common is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro 
> Some plugins require plugin Window System API to be installed.
> The plugin Window System API is requested in implementation version incubator-netbeans-release-334-on-20180708.  The following plugin is affected:       Payara Micro  Some plugins not installed to avoid potential installation problems.

```

This is my info about my netbeans and im using jdk 8. 
![image](https://user-images.githubusercontent.com/38962557/46250561-c2ae9480-c402-11e8-83b1-02dbc9fa3d59.png)

¿Any idea?

**Comment by jGauravGupta** [comment]
As per above screenshot, your IDE build number is unknown, perhaps build is not compatible with plugin.

I will recommend either download the Apache NetBeans IDE 9.0 (Build incubator-netbeans-release-334-on-20180708) or you may download the Apache NetBeans IDE 9.0 with pre-installed Payara plugins from here :  https://github.com/payara/ecosystem-netbeans-plugin/releases/download/1.4/PayaraPlugins.1.4.with.Apache.NetBeans.IDE.9.0.zip

**Comment by jGauravGupta** [comment]
Closing this issue, If problem occurred with Apache NetBeans IDE 9.0 (Build incubator-netbeans-release-334-on-20180708) or with pre-installed Payara plugins bundle, please reopen the ticket.

**Comment by Mustafa-Halimeh** [comment]
I have the same response message from netbeans.
This my netbeans product information:
Product Version: NetBeans IDE 8.2 (Build 201610071157)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_212; Java HotSpot(TM) 64-Bit Server VM 25.212-b10
Runtime: Java(TM) SE Runtime Environment 1.8.0_212-b10
System: Linux version 4.12.14-lp150.12.48-default running on amd64; UTF-8; en_US (nb)

Is there a way to resolve this for the give netbeans 8.2 (201610071157)), or what?
Thanks
